openapi: 3.0.3
info:
  title: Ledger API
  contact: {}
  version: v1
paths:
  /_info:
    get:
      tags:
        - ledger.v1
      summary: Show server information
      operationId: getInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigInfoResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/_info:
    get:
      summary: Get information about a ledger
      operationId: getLedgerInfo
      tags:
        - ledger.v1
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LedgerInfoResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/accounts:
    head:
      summary: Count the accounts from a ledger
      operationId: countAccounts
      tags:
        - ledger.v1
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: address
          in: query
          description: >-
            Filter accounts by address pattern (regular expression placed
            between ^ and $).
          schema:
            type: string
            example: users:.+
        - name: metadata
          in: query
          description: >-
            Filter accounts by metadata key value pairs. The filter can be used
            like this metadata[key]=value1&metadata[a.nested.key]=value2
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties: true
          example: metadata[key]=value1&metadata[a.nested.key]=value2
      responses:
        '204':
          description: OK
          headers:
            Count:
              schema:
                type: integer
                format: int64
                minimum: 0
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
    get:
      summary: List accounts from a ledger
      description: List accounts from a ledger, sorted by address in descending order.
      operationId: listAccounts
      tags:
        - ledger.v1
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: pageSize
          in: query
          description: |
            The maximum number of results to return per page.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
        - name: page_size
          x-speakeasy-ignore: true
          in: query
          description: |
            The maximum number of results to return per page.
            Deprecated, please use `pageSize` instead.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
          deprecated: true
        - name: after
          in: query
          description: >-
            Pagination cursor, will return accounts after given address, in
            descending order.
          schema:
            type: string
            example: users:003
        - name: address
          in: query
          description: >-
            Filter accounts by address pattern (regular expression placed
            between ^ and $).
          schema:
            type: string
            example: users:.+
        - name: metadata
          in: query
          description: >-
            Filter accounts by metadata key value pairs. Nested objects can be
            used as seen in the example below.
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties: true
          example: metadata[key]=value1&metadata[a.nested.key]=value2
        - name: balance
          in: query
          description: Filter accounts by their balance (default operator is gte)
          schema:
            type: integer
            format: int64
            example: 2400
        - name: balanceOperator
          x-speakeasy-ignore: true
          in: query
          description: >
            Operator used for the filtering of balances can be greater
            than/equal, less than/equal, greater than, less than, equal or not.
          schema:
            type: string
            enum:
              - gte
              - lte
              - gt
              - lt
              - e
              - ne
            example: gte
        - name: balance_operator
          x-speakeasy-ignore: true
          in: query
          description: >
            Operator used for the filtering of balances can be greater
            than/equal, less than/equal, greater than, less than, equal or not.

            Deprecated, please use `balanceOperator` instead.
          schema:
            type: string
            enum:
              - gte
              - lte
              - gt
              - lt
              - e
              - ne
            example: gte
          deprecated: true
        - name: cursor
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
        - name: pagination_token
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.

            Deprecated, please use `cursor` instead.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
          deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsCursorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/accounts/{address}:
    get:
      summary: Get account by its address
      operationId: getAccount
      tags:
        - ledger.v1
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: address
          in: path
          description: >
            Exact address of the account. It must match the following regular
            expressions pattern:

            ```

            ^\w+(:\w+)*$

            ```
          required: true
          schema:
            type: string
            example: users:001
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/accounts/{address}/metadata:
    post:
      summary: Add metadata to an account
      operationId: addMetadataToAccount
      tags:
        - ledger.v1
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: address
          in: path
          description: >
            Exact address of the account. It must match the following regular
            expressions pattern:

            ```

            ^\w+(:\w+)*$

            ```
          required: true
          schema:
            type: string
            example: users:001
      requestBody:
        description: metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
        required: true
      responses:
        '204':
          description: No Content
          headers:
            Idempotency-Hit:
              description: Indicates that the request was processed using an idempotency key that was already used
              schema:
                type: string
                example: "true"
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/mapping:
    get:
      tags:
        - ledger.v1
      operationId: getMapping
      summary: Get the mapping of a ledger
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
    put:
      tags:
        - ledger.v1
      operationId: updateMapping
      summary: Update the mapping of a ledger
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mapping'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/script:
    post:
      deprecated: true
      tags:
        - ledger.v1
      operationId: runScript
      summary: Execute a Numscript
      description: >
        This route is deprecated, and has been merged into `POST
        /{ledger}/transactions`.
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: preview
          in: query
          description: >-
            Set the preview mode. Preview mode doesn't add the logs to the
            database or publish a message to the message broker.
          schema:
            type: boolean
            example: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Script'
      responses:
        '200':
          description: >
            On success, it will return a 200 status code, and the resulting
            transaction under the `transaction` field.


            On failure, it will also return a 200 status code, and the following
            fields:
              - `details`: contains a URL. When there is an error parsing Numscript, the result can be difficult to read—the provided URL will render the error in an easy-to-read format.
              - `errorCode` and `error_code` (deprecated): contains the string code of the error
              - `errorMessage` and `error_message` (deprecated): contains a human-readable indication of what went wrong, for example that an account had insufficient funds, or that there was an error in the provided Numscript.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScriptResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/stats:
    get:
      tags:
        - ledger.v1
      operationId: readStats
      summary: Get statistics from a ledger
      description: >
        Get statistics from a ledger. (aggregate metrics on accounts and
        transactions)
      parameters:
        - name: ledger
          in: path
          description: name of the ledger
          required: true
          schema:
            type: string
            example: ledger001
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/transactions:
    head:
      tags:
        - ledger.v1
      summary: Count the transactions from a ledger
      operationId: countTransactions
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: reference
          in: query
          description: Filter transactions by reference field.
          schema:
            type: string
            example: ref:001
        - name: account
          in: query
          description: >-
            Filter transactions with postings involving given account, either as
            source or destination (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: source
          in: query
          description: >-
            Filter transactions with postings involving given account at source
            (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: destination
          in: query
          description: >-
            Filter transactions with postings involving given account at
            destination (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: startTime
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: start_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).

            Deprecated, please use `startTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: endTime
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: end_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).

            Deprecated, please use `endTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: metadata
          in: query
          description: >-
            Filter transactions by metadata key value pairs. Nested objects can
            be used as seen in the example below.
          style: deepObject
          explode: true
          schema:
            type: object
            properties: {}
          example: metadata[key]=value1&metadata[a.nested.key]=value2
      responses:
        '200':
          description: OK
          headers:
            Count:
              schema:
                type: integer
                format: int64
                minimum: 0
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
    get:
      tags:
        - ledger.v1
      summary: List transactions from a ledger
      description: List transactions from a ledger, sorted by txid in descending order.
      operationId: listTransactions
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: pageSize
          in: query
          description: |
            The maximum number of results to return per page.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
        - name: page_size
          x-speakeasy-ignore: true
          in: query
          description: |
            The maximum number of results to return per page.
            Deprecated, please use `pageSize` instead.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
          deprecated: true
        - name: after
          in: query
          description: >-
            Pagination cursor, will return transactions after given txid (in
            descending order).
          schema:
            type: string
            example: 1234
        - name: reference
          in: query
          description: Find transactions by reference field.
          schema:
            type: string
            example: ref:001
        - name: account
          in: query
          description: >-
            Filter transactions with postings involving given account, either as
            source or destination (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: source
          in: query
          description: >-
            Filter transactions with postings involving given account at source
            (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: destination
          in: query
          description: >-
            Filter transactions with postings involving given account at
            destination (regular expression placed between ^ and $).
          schema:
            type: string
            example: users:001
        - name: startTime
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: start_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).

            Deprecated, please use `startTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: endTime
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: end_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).

            Deprecated, please use `endTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: cursor
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
        - name: pagination_token
          x-speakeasy-ignore: true
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.

            Deprecated, please use `cursor` instead.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
          deprecated: true
        - name: metadata
          in: query
          description: >-
            Filter transactions by metadata key value pairs. Nested objects can
            be used as seen in the example below.
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsCursorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
    post:
      tags:
        - ledger.v1
      summary: Create a new transaction to a ledger
      operationId: createTransaction
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: preview
          in: query
          description: >-
            Set the preview mode. Preview mode doesn't add the logs to the
            database or publish a message to the message broker.
          schema:
            type: boolean
            example: true
      requestBody:
        required: true
        description: |
          The request body must contain at least one of the following objects:
            - `postings`: suitable for simple transactions
            - `script`: enabling more complex transactions with Numscript
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTransaction'
      responses:
        '200':
          description: OK
          headers:
            Idempotency-Hit:
              description: Indicates that the request was processed using an idempotency key that was already used
              schema:
                type: string
                example: "true"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/transactions/{txid}:
    get:
      tags:
        - ledger.v1
      summary: Get transaction from a ledger by its ID
      operationId: getTransaction
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: txid
          in: path
          description: Transaction ID.
          required: true
          schema:
            type: integer
            format: bigint
            minimum: 0
            example: 1234
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/transactions/{txid}/metadata:
    post:
      tags:
        - ledger.v1
      summary: Set the metadata of a transaction by its ID
      operationId: addMetadataOnTransaction
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: txid
          in: path
          description: Transaction ID.
          required: true
          schema:
            type: integer
            format: bigint
            minimum: 0
            example: 1234
      requestBody:
        required: true
        description: metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metadata'
      responses:
        '204':
          description: No Content
          headers:
            Idempotency-Hit:
              description: Indicates that the request was processed using an idempotency key that was already used
              schema:
                type: string
                example: "true"
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/transactions/{txid}/revert:
    post:
      tags:
        - ledger.v1
      operationId: revertTransaction
      summary: Revert a ledger transaction by its ID
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: txid
          in: path
          description: Transaction ID.
          required: true
          schema:
            type: integer
            format: bigint
            minimum: 0
            example: 1234
        - name: disableChecks
          in: query
          description: Allow to disable balances checks
          required: false
          schema:
            type: boolean
      responses:
        '201':
          description: OK
          headers:
            Idempotency-Hit:
              description: Indicates that the request was processed using an idempotency key that was already used
              schema:
                type: string
                example: "true"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/transactions/batch:
    post:
      tags:
        - ledger.v1
      summary: Create a new batch of transactions to a ledger
      operationId: CreateTransactions
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transactions'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:write
  /{ledger}/balances:
    get:
      tags:
        - ledger.v1
      summary: Get the balances from a ledger's account
      operationId: getBalances
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: address
          in: query
          description: >-
            Filter balances involving given account, either as source or
            destination.
          schema:
            type: string
            example: users:001
        - name: pageSize
          in: query
          description: |
            The maximum number of results to return per page.
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
        - name: after
          in: query
          description: >-
            Pagination cursor, will return accounts after given address, in
            descending order.
          schema:
            type: string
            example: users:003
        - name: cursor
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
        - name: pagination_token
          x-speakeasy-ignore: true
          in: query
          description: |-
            Parameter used in pagination requests.
            Set to the value of next for the next page of results.
            Set to the value of previous for the previous page of results.
            Deprecated, please use `cursor` instead.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
          deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancesCursorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/aggregate/balances:
    get:
      tags:
        - ledger.v1
      summary: Get the aggregated balances from selected accounts
      operationId: getBalancesAggregated
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: address
          in: query
          description: >-
            Filter balances involving given account, either as source or
            destination.
          schema:
            type: string
            example: users:001
        - name: useInsertionDate
          in: query
          description: Use insertion date instead of effective date
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregateBalancesResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
  /{ledger}/logs:
    get:
      tags:
        - ledger.v1
      summary: List the logs from a ledger
      description: List the logs from a ledger, sorted by ID in descending order.
      operationId: listLogs
      parameters:
        - name: ledger
          in: path
          description: Name of the ledger.
          required: true
          schema:
            type: string
            example: ledger001
        - name: pageSize
          in: query
          description: |
            The maximum number of results to return per page.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
        - name: page_size
          x-speakeasy-ignore: true
          in: query
          description: |
            The maximum number of results to return per page.
            Deprecated, please use `pageSize` instead.
          example: 100
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 1000
          deprecated: true
        - name: after
          in: query
          description: >-
            Pagination cursor, will return the logs after a given ID. (in
            descending order).
          schema:
            type: string
            example: 1234
        - name: startTime
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: start_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred after this timestamp.

            The format is RFC3339 and is inclusive (for example,
            "2023-01-02T15:04:01Z" includes the first second of 4th minute).

            Deprecated, please use `startTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: endTime
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).
          schema:
            type: string
            format: date-time
        - name: end_time
          x-speakeasy-ignore: true
          in: query
          description: >
            Filter transactions that occurred before this timestamp.

            The format is RFC3339 and is exclusive (for example,
            "2023-01-02T15:04:01Z" excludes the first second of 4th minute).

            Deprecated, please use `endTime` instead.
          schema:
            type: string
            format: date-time
          deprecated: true
        - name: cursor
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
        - name: pagination_token
          x-speakeasy-ignore: true
          in: query
          description: >
            Parameter used in pagination requests. Maximum page size is set to
            1000.

            Set to the value of next for the next page of results.

            Set to the value of previous for the previous page of results.

            No other parameters can be set when this parameter is set.

            Deprecated, please use `cursor` instead.
          schema:
            type: string
            example: aHR0cHM6Ly9nLnBhZ2UvTmVrby1SYW1lbj9zaGFyZQ==
          deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogsCursorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - Authorization:
            - ledger:read
components:
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '/oauth/token'
          refreshUrl: '/oauth/token'
          scopes: { }

  schemas:
    AccountsCursorResponse:
      type: object
      required:
        - cursor
      properties:
        cursor:
          type: object
          description: Paginated cursor wrapping the list of accounts
          required:
            - pageSize
            - hasMore
            - data
          properties:
            pageSize:
              type: integer
              format: int64
              minimum: 1
              maximum: 1000
              example: 15
            hasMore:
              type: boolean
              example: false
            previous:
              type: string
              example: YXVsdCBhbmQgYSBtYXhpbXVtIG1heF9yZXN1bHRzLol=
            next:
              type: string
              example: ''
            data:
              type: array
              items:
                $ref: '#/components/schemas/Account'
    BalancesCursorResponse:
      type: object
      required:
        - cursor
      properties:
        cursor:
          type: object
          description: Paginated cursor wrapping the list of balances
          required:
            - pageSize
            - hasMore
            - data
          properties:
            pageSize:
              type: integer
              format: int64
              minimum: 1
              maximum: 1000
              example: 15
            hasMore:
              type: boolean
              example: false
            previous:
              type: string
              example: YXVsdCBhbmQgYSBtYXhpbXVtIG1heF9yZXN1bHRzLol=
            next:
              type: string
              example: ''
            data:
              type: array
              items:
                $ref: '#/components/schemas/AccountsBalances'
    TransactionsCursorResponse:
      type: object
      required:
        - cursor
      properties:
        cursor:
          type: object
          description: Paginated cursor wrapping the list of transactions
          required:
            - pageSize
            - hasMore
            - data
          properties:
            pageSize:
              type: integer
              format: int64
              minimum: 1
              maximum: 1000
              example: 15
            hasMore:
              type: boolean
              example: false
            previous:
              type: string
              example: YXVsdCBhbmQgYSBtYXhpbXVtIG1heF9yZXN1bHRzLol=
            next:
              type: string
              example: ''
            data:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
    LogsCursorResponse:
      type: object
      required:
        - cursor
      properties:
        cursor:
          type: object
          description: Paginated cursor wrapping the list of logs
          required:
            - pageSize
            - hasMore
            - data
          properties:
            pageSize:
              type: integer
              format: int64
              minimum: 1
              maximum: 1000
              example: 15
            hasMore:
              type: boolean
              example: false
            previous:
              type: string
              example: YXVsdCBhbmQgYSBtYXhpbXVtIG1heF9yZXN1bHRzLol=
            next:
              type: string
              example: ''
            data:
              type: array
              items:
                $ref: '#/components/schemas/Log'
    AccountResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/AccountWithVolumesAndBalances'
    AggregateBalancesResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/AssetsBalances'
    Config:
      type: object
      description: Configuration the ledger server is running with
      properties:
        storage:
          $ref: '#/components/schemas/LedgerStorage'
      required:
        - storage
    LedgerStorage:
      type: object
      description: Storage backend the ledgers are held in
      properties:
        driver:
          type: string
          description: Name of the storage driver backing the ledgers
        ledgers:
          type: array
          description: Names of the ledgers held in this storage backend
          items:
            type: string
      required:
        - driver
        - ledgers
    Metadata:
      type: object
      nullable: true
      description: Arbitrary key/value pairs attached to the resource
      additionalProperties: {}
    ConfigInfo:
      type: object
      description: Configuration and version information for the ledger server
      properties:
        config:
          $ref: '#/components/schemas/Config'
        server:
          type: string
          description: Name of the server serving the API
        version:
          type: string
          description: Version of the ledger service
        experimentalFeatures:
          type: array
          description: Experimental feature flags enabled on this deployment
          items:
            type: string
      required:
        - config
        - server
        - version
    ScriptResponse:
      type: object
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorsEnum'
        errorMessage:
          type: string
          description: Human-readable description of the error
          example: account had insufficient funds
        details:
          type: string
          description: >-
            Optional link carrying additional context about the error, such as a Numscript playground URL
            reproducing it
          example: >-
            https://play.numscript.org/?payload=eyJlcnJvciI6ImFjY291bnQgaGFkIGluc3VmZmljaWVudCBmdW5kcyJ9
        transaction:
          $ref: '#/components/schemas/Transaction'
    Account:
      type: object
      required:
        - address
      properties:
        address:
          type: string
          description: The account address, a colon-separated segmented path such as users:001
          example: users:001
        type:
          type: string
          description: Free-form classification of the account
          example: virtual
        metadata:
          type: object
          description: Arbitrary key/value pairs attached to the account
          additionalProperties: true
          example:
            admin: true
            a:
              nested:
                key: value
    AccountWithVolumesAndBalances:
      type: object
      description: An account together with its volumes and net balances per asset
      required:
        - address
      properties:
        address:
          type: string
          description: The account address, a colon-separated segmented path such as users:001
          example: users:001
        type:
          type: string
          description: Free-form classification of the account
          example: virtual
        metadata:
          type: object
          description: Arbitrary key/value pairs attached to the account
          additionalProperties: true
          example:
            admin: true
            a:
              nested:
                key: value
        volumes:
          $ref: '#/components/schemas/Volumes'
        balances:
          type: object
          description: Net balance per asset, equal to input minus output
          additionalProperties:
            type: integer
            format: bigint
          example:
            COIN: 100
    AccountsBalances:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AssetsBalances'
      example:
        account1:
          USD: 100
          EUR: 23
        account2:
          CAD: 20
          JPY: 21
    AssetsBalances:
      type: object
      description: Balances keyed by asset
      additionalProperties:
        type: integer
        format: int64
      example:
        USD: 100
        EUR: 12
    Contract:
      type: object
      properties:
        account:
          type: string
          description: Account address, or pattern, the contract applies to
          example: users:001
        expr:
          type: object
          description: Expression the account's balances must satisfy
      required:
        - accounts
        - expr
    Mapping:
      type: object
      nullable: true
      description: Contracts constraining the balances a ledger's accounts may hold
      required:
        - contracts
      properties:
        contracts:
          type: array
          description: Constraints enforced on the ledger's accounts
          items:
            $ref: '#/components/schemas/Contract'
    Posting:
      type: object
      properties:
        amount:
          type: integer
          format: bigint
          minimum: 0
          description: Amount to move, as an arbitrary-precision integer expressed in the asset's smallest unit
          example: 100
        asset:
          type: string
          description: The asset being moved, optionally carrying a scale suffix such as USD/2
          example: COIN
        destination:
          type: string
          description: Address of the account credited by this posting
          example: users:002
        source:
          type: string
          description: Address of the account debited by this posting
          example: users:001
      required:
        - amount
        - asset
        - destination
        - source
    Script:
      type: object
      properties:
        plain:
          type: string
          description: The Numscript program to execute
          example: "vars {\naccount $user\n}\nsend [COIN 10] (\n\tsource = @world\n\tdestination = $user\n)\n"
        vars:
          type: object
          description: Values bound to the script's declared variables, keyed by variable name
          additionalProperties: true
          example:
            user: users:042
        reference:
          type: string
          example: order_1234
          description: Reference to attach to the generated transaction
        metadata:
          $ref: '#/components/schemas/Metadata'
      required:
        - plain
    Transaction:
      type: object
      description: A transaction recorded in the ledger, carrying its postings and metadata
      properties:
        timestamp:
          type: string
          format: date-time
          description: >-
            The transaction time: when the transaction is considered to have occurred. See
            [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
        postings:
          type: array
          description: The fund movements making up the transaction
          items:
            $ref: '#/components/schemas/Posting'
        reference:
          type: string
          description: Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
          example: ref:001
        metadata:
          $ref: '#/components/schemas/Metadata'
        txid:
          type: integer
          format: bigint
          minimum: 0
          description: Unique sequential identifier for this transaction within the ledger
        preCommitVolumes:
          $ref: '#/components/schemas/AggregatedVolumes'
        postCommitVolumes:
          $ref: '#/components/schemas/AggregatedVolumes'
      required:
        - postings
        - timestamp
        - txid
    TransactionData:
      type: object
      required:
        - postings
      properties:
        postings:
          type: array
          description: The fund movements making up the transaction
          items:
            $ref: '#/components/schemas/Posting'
        reference:
          type: string
          description: Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
          example: ref:001
        metadata:
          $ref: '#/components/schemas/Metadata'
        timestamp:
          type: string
          format: date-time
          description: >-
            The transaction time to record, letting you backdate or postdate the transaction. See
            [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
    Transactions:
      required:
        - transactions
      type: object
      properties:
        transactions:
          type: array
          description: The transactions to create, applied in order
          items:
            $ref: '#/components/schemas/TransactionData'
    PostTransaction:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: >-
            The transaction time to record, letting you backdate or postdate the transaction. See
            [bi-temporality](https://docs.formance.com/modules/ledger/working-with/bi-temporality)
        postings:
          type: array
          description: Fund movements to apply. Mutually exclusive with script
          items:
            $ref: '#/components/schemas/Posting'
        script:
          type: object
          description: A Numscript program executed to produce the postings. Mutually exclusive with postings
          properties:
            plain:
              type: string
              example: "vars {\naccount $user\n}\nsend [COIN 10] (\n\tsource = @world\n\tdestination = $user\n)\n"
            vars:
              type: object
              additionalProperties: true
              example:
                user: users:042
          required:
            - plain
        reference:
          type: string
          description: Optional caller-supplied identifier, unique within the ledger, used to deduplicate transactions
          example: ref:001
        metadata:
          $ref: '#/components/schemas/Metadata'
    Stats:
      type: object
      description: Aggregate counts for a ledger
      properties:
        accounts:
          type: integer
          format: int64
          minimum: 0
          description: Total number of accounts in the ledger
        transactions:
          type: integer
          format: int64
          minimum: 0
          description: Total number of transactions in the ledger
      required:
        - accounts
        - transactions
    Log:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
          description: Unique sequential identifier for this log entry within the ledger
          example: 1234
        type:
          type: string
          description: The type of operation this log represents
          enum:
            - NEW_TRANSACTION
            - SET_METADATA
        data:
          type: object
          description: The payload of the log entry, whose shape depends on the log type
          additionalProperties: true
        hash:
          type: string
          description: SHA256 hash of the log entry, chained from the previous log for integrity verification
          example: 9ee060170400f556b7e1575cb13f9db004f150a08355c7431c62bc639166431e
        date:
          type: string
          format: date-time
          description: Timestamp when the operation was recorded
      required:
        - id
        - type
        - data
        - hash
        - date
    TransactionsResponse:
      type: object
      properties:
        data:
          items:
            $ref: '#/components/schemas/Transaction'
          type: array
          description: The transactions that were created
      required:
        - data
    TransactionResponse:
      properties:
        data:
          $ref: '#/components/schemas/Transaction'
      type: object
      required:
        - data
    StatsResponse:
      properties:
        data:
          $ref: '#/components/schemas/Stats'
      type: object
      required:
        - data
    MappingResponse:
      properties:
        data:
          $ref: '#/components/schemas/Mapping'
      type: object
    ConfigInfoResponse:
      properties:
        data:
          $ref: '#/components/schemas/ConfigInfo'
      type: object
      required:
        - data
    Volume:
      type: object
      properties:
        input:
          type: integer
          format: bigint
          description: Total amount credited for this asset
        output:
          type: integer
          format: bigint
          description: Total amount debited for this asset
        balance:
          type: integer
          format: bigint
          description: Net balance, equal to input minus output
      required:
        - input
        - output
      example:
        input: 100
        output: 20
        balance: 80
    Volumes:
      type: object
      description: Volumes per asset for a single account
      additionalProperties:
        $ref: '#/components/schemas/Volume'
      example:
        USD:
          input: 100
          output: 10
          balance: 90
        EUR:
          input: 100
          output: 10
          balance: 90
    AggregatedVolumes:
      type: object
      description: Volumes aggregated per account and per asset
      additionalProperties:
        $ref: '#/components/schemas/Volumes'
      example:
        orders:1:
          USD:
            input: 100
            output: 10
            balance: 90
        orders:2:
          USD:
            input: 100
            output: 10
            balance: 90
    ErrorResponse:
      type: object
      required:
        - errorCode
        - errorMessage
      properties:
        errorCode:
          $ref: '#/components/schemas/ErrorsEnum'
        errorMessage:
          type: string
          description: Human-readable description of the error
          example: '[INSUFFICIENT_FUND] account had insufficient funds'
        details:
          type: string
          description: >-
            Optional link carrying additional context about the error, such as a Numscript playground URL
            reproducing it
          example: >-
            https://play.numscript.org/?payload=eyJlcnJvciI6ImFjY291bnQgaGFkIGluc3VmZmljaWVudCBmdW5kcyJ9
    ErrorsEnum:
      type: string
      description: Machine-readable error code identifying the failure
      enum:
        - INTERNAL
        - INSUFFICIENT_FUND
        - VALIDATION
        - CONFLICT
        - NO_SCRIPT
        - COMPILATION_FAILED
        - METADATA_OVERRIDE
        - NOT_FOUND
        - TIMEOUT
      example: INSUFFICIENT_FUND
    LedgerInfoResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/LedgerInfo'
    LedgerInfo:
      type: object
      description: Runtime information about a ledger, including the state of its storage migrations
      properties:
        name:
          type: string
          description: Name of the ledger
          example: ledger001
        storage:
          type: object
          description: Storage backend information, including the applied migrations
          properties:
            migrations:
              type: array
              items:
                $ref: '#/components/schemas/MigrationInfo'
    MigrationInfo:
      type: object
      properties:
        version:
          type: string
          minimum: 0
          description: Sequence number of the migration
          example: 11
        name:
          type: string
          description: Name of the migration
          example: migrations:001
        date:
          type: string
          format: date-time
          description: When the migration was applied
        state:
          type: string
          description: Current state of the migration
          enum:
            - TO DO
            - DONE
